In [0]:
import pandas as pd
import numpy as np

In [0]:
# 데이터 불러오기
df = pd.read_csv('titanic_train.csv')

In [3]:
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [4]:
# 데이터 확인하기
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB

In [0]:
# sex는 label encoding으로 바꾸어 주어야 할 것 같다.
# age/cabin/embarked에 결측치 있는 것 알 수 있다.

In [6]:
# 결측치 없는 거 맞는지 다시 한 번 확인
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [0]:
# 전처리 하기 위해 label encoding 불러오기
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [8]:
df['Sex'].head()

0      male
1    female
2    female
3    female
4      male
Name: Sex, dtype: object

In [9]:
encoder = LabelEncoder()
encoder.fit(df['Sex'])
labels = encoder.transform(df['Sex'])
labels

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1])

In [10]:
# 근데 위에 모델은 ML할 때 가중치를 부여받을 수 있으니, one-hot encoding으로 바꾸어 주어야 겠다.
encoder = LabelEncoder()
encoder.fit(df['Sex'])
new_labels = encoder.transform(df['Sex'])
new_labels = new_labels.reshape(-1, 1)

one_hot = OneHotEncoder()
one_hot.fit(new_labels)
one_hot_labels = one_hot.transform(new_labels)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)

In [11]:
print(one_hot_labels)

  (0, 1)	1.0
  (1, 0)	1.0
  (2, 0)	1.0
  (3, 0)	1.0
  (4, 1)	1.0
  (5, 1)	1.0
  (6, 1)	1.0
  (7, 1)	1.0
  (8, 0)	1.0
  (9, 0)	1.0
  (10, 0)	1.0
  (11, 0)	1.0
  (12, 1)	1.0
  (13, 1)	1.0
  (14, 0)	1.0
  (15, 0)	1.0
  (16, 1)	1.0
  (17, 1)	1.0
  (18, 0)	1.0
  (19, 0)	1.0
  (20, 1)	1.0
  (21, 1)	1.0
  (22, 0)	1.0
  (23, 1)	1.0
  (24, 0)	1.0
  :	:
  (866, 0)	1.0
  (867, 1)	1.0
  (868, 1)	1.0
  (869, 1)	1.0
  (870, 1)	1.0
  (871, 0)	1.0
  (872, 1)	1.0
  (873, 1)	1.0
  (874, 0)	1.0
  (875, 0)	1.0
  (876, 1)	1.0
  (877, 1)	1.0
  (878, 1)	1.0
  (879, 0)	1.0
  (880, 0)	1.0
  (881, 1)	1.0
  (882, 0)	1.0
  (883, 1)	1.0
  (884, 1)	1.0
  (885, 0)	1.0
  (886, 1)	1.0
  (887, 0)	1.0
  (888, 0)	1.0
  (889, 1)	1.0
  (890, 1)	1.0

In [0]:
# 근데 위에 것은 2차원이라 어짜피 사용 못할 듯..??;;;

In [13]:
# 결측치 처리 - 평균으로 age만 해주자
df['Age'].mean()

29.69911764705882

In [32]:
df.fillna(df['Age'].mean(), inplace = True)
df.head()

   PassengerId  Survived  Pclass  ...    Cabin Embarked  altered_sex
0            1         0       3  ...  29.6991        S            1
1            2         1       1  ...      C85        C            0
2            3         1       3  ...  29.6991        S            0
3            4         1       1  ...     C123        S            0
4            5         0       3  ...  29.6991        S            1

[5 rows x 13 columns]

In [0]:
df['altered_sex'] = labels

In [31]:
df.head()

   PassengerId  Survived  Pclass  ...    Cabin Embarked  altered_sex
0            1         0       3  ...  29.6991        S            1
1            2         1       1  ...      C85        C            0
2            3         1       3  ...  29.6991        S            0
3            4         1       1  ...     C123        S            0
4            5         0       3  ...  29.6991        S            1

[5 rows x 13 columns]

In [33]:
# 결측치 없는 거 맞는지 다시 한 번 확인
df.isnull().sum()
##???? Embarked/Cabin 건든게 없는데요...????

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
altered_sex    0
dtype: int64

In [34]:
df.describe()

       PassengerId    Survived      Pclass  ...       Parch        Fare  altered_sex
count   891.000000  891.000000  891.000000  ...  891.000000  891.000000   891.000000
mean    446.000000    0.383838    2.308642  ...    0.381594   32.204208     0.647587
std     257.353842    0.486592    0.836071  ...    0.806057   49.693429     0.477990
min       1.000000    0.000000    1.000000  ...    0.000000    0.000000     0.000000
25%     223.500000    0.000000    2.000000  ...    0.000000    7.910400     0.000000
50%     446.000000    0.000000    3.000000  ...    0.000000   14.454200     1.000000
75%     668.500000    1.000000    3.000000  ...    0.000000   31.000000     1.000000
max     891.000000    1.000000    3.000000  ...    6.000000  512.329200     1.000000

[8 rows x 8 columns]

In [0]:
# 데이터 컬럼 나누기
# Data에는 예측하고자 하는 Survived값을 제와하고, 이 값은 target으로 설정해놓기
# 숫자 있는 걸로만 data로 가져오쟈...(그래서 age/altered_sex 위에서 처리해준거니까)

In [37]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'altered_sex'],
      dtype='object')

In [0]:
data = df.drop(['Survived', 'PassengerId', 'Name', 'Sex','Ticket', 'Fare', 'Cabin', 'Embarked' ], axis=1)

In [0]:
target = df['Survived']

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
#data split
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.1, random_state=0)

In [0]:
from sklearn.neighbors import KNeighborsClassifier

In [0]:
#모델 만들기
model = KNeighborsClassifier(n_neighbors=3).fit(X_train, y_train)

In [52]:
#예측하기
pred = model.predict(X_test)
pred

array([0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0])

In [55]:
#얼마나 맞추었나 accuracy 추측하기
(pred == y_test).sum()/len(pred)

0.7888888888888889

In [56]:
df = pd.DataFrame({'y_test': y_test, 'prediction': pred})
df

     y_test  prediction
495       0           0
648       0           0
278       0           0
31        1           1
255       1           0
298       1           0
609       1           1
318       1           1
484       1           0
367       1           1
704       0           0
346       1           0
196       0           0
535       1           1
310       1           1
14        0           1
350       0           0
145       0           0
614       0           0
803       1           1
144       0           0
708       1           1
778       0           0
270       0           0
474       0           1
319       1           1
519       0           0
141       1           1
880       1           1
642       0           0
..      ...         ...
60        0           0
567       0           0
496       1           1
766       0           0
8         1           0
890       0           0
796       1           1
848       0           0
530       1           1
887       1           1
316       1           1
712       1           1
34        0           1
77        0           0
676       0           0
726       1           0
27        0           1
30        0           0
202       0           0
181       0           0
768       0           0
489       1           1
312       0           0
764       0           0
397       0           0
627       1           0
380       1           1
483       1           1
516       1           1
505       0           0

[90 rows x 2 columns]

In [57]:
acc_tr = model.score(X_train, y_train)
acc_test = model.score(X_test, y_test)
print('훈련 셋의 정확도 : {:.2f}'.format(acc_tr))
print('테스트 셋의 정확도 : {:.2f}'.format(acc_test))

훈련 셋의 정확도 : 0.86
테스트 셋의 정확도 : 0.79

In [58]:
# for문을 돌려보쟈

training_accuracy = []
test_accuracy = []
k_num = range(1,101)

for n in k_num:
    model = KNeighborsClassifier(n_neighbors=n)
    model.fit(X_train, y_train)
    
    acc_tr = model.score(X_train, y_train)
    acc_test = model.score(X_test, y_test)
    
    training_accuracy.append(acc_tr)
    test_accuracy.append(acc_test)
    
    print("K: {}, tr_acc : {:.2f}, test_acc : {:.2f}".format(n, acc_tr, acc_test))

K: 1, tr_acc : 0.91, test_acc : 0.78
K: 2, tr_acc : 0.85, test_acc : 0.77
K: 3, tr_acc : 0.86, test_acc : 0.79
K: 4, tr_acc : 0.85, test_acc : 0.74
K: 5, tr_acc : 0.85, test_acc : 0.79
K: 6, tr_acc : 0.83, test_acc : 0.76
K: 7, tr_acc : 0.84, test_acc : 0.72
K: 8, tr_acc : 0.83, test_acc : 0.72
K: 9, tr_acc : 0.83, test_acc : 0.71
K: 10, tr_acc : 0.82, test_acc : 0.70
K: 11, tr_acc : 0.83, test_acc : 0.73
K: 12, tr_acc : 0.80, test_acc : 0.72
K: 13, tr_acc : 0.82, test_acc : 0.76
K: 14, tr_acc : 0.80, test_acc : 0.71
K: 15, tr_acc : 0.80, test_acc : 0.73
K: 16, tr_acc : 0.78, test_acc : 0.72
K: 17, tr_acc : 0.79, test_acc : 0.70
K: 18, tr_acc : 0.78, test_acc : 0.70
K: 19, tr_acc : 0.78, test_acc : 0.69
K: 20, tr_acc : 0.78, test_acc : 0.71
K: 21, tr_acc : 0.77, test_acc : 0.68
K: 22, tr_acc : 0.76, test_acc : 0.71
K: 23, tr_acc : 0.77, test_acc : 0.71
K: 24, tr_acc : 0.76, test_acc : 0.70
K: 25, tr_acc : 0.77, test_acc : 0.71
K: 26, tr_acc : 0.75, test_acc : 0.68
K: 27, tr_acc : 0.76, test_acc : 0.67
K: 28, tr_acc : 0.76, test_acc : 0.68
K: 29, tr_acc : 0.76, test_acc : 0.69
K: 30, tr_acc : 0.74, test_acc : 0.68
K: 31, tr_acc : 0.75, test_acc : 0.68
K: 32, tr_acc : 0.74, test_acc : 0.67
K: 33, tr_acc : 0.76, test_acc : 0.66
K: 34, tr_acc : 0.74, test_acc : 0.67
K: 35, tr_acc : 0.74, test_acc : 0.64
K: 36, tr_acc : 0.74, test_acc : 0.66
K: 37, tr_acc : 0.72, test_acc : 0.62
K: 38, tr_acc : 0.72, test_acc : 0.64
K: 39, tr_acc : 0.73, test_acc : 0.66
K: 40, tr_acc : 0.71, test_acc : 0.66
K: 41, tr_acc : 0.71, test_acc : 0.62
K: 42, tr_acc : 0.70, test_acc : 0.64
K: 43, tr_acc : 0.71, test_acc : 0.62
K: 44, tr_acc : 0.70, test_acc : 0.64
K: 45, tr_acc : 0.70, test_acc : 0.62
K: 46, tr_acc : 0.69, test_acc : 0.64
K: 47, tr_acc : 0.70, test_acc : 0.64
K: 48, tr_acc : 0.69, test_acc : 0.66
K: 49, tr_acc : 0.69, test_acc : 0.62
K: 50, tr_acc : 0.68, test_acc : 0.64
K: 51, tr_acc : 0.68, test_acc : 0.63
K: 52, tr_acc : 0.67, test_acc : 0.61
K: 53, tr_acc : 0.67, test_acc : 0.62
K: 54, tr_acc : 0.66, test_acc : 0.62
K: 55, tr_acc : 0.67, test_acc : 0.62
K: 56, tr_acc : 0.66, test_acc : 0.60
K: 57, tr_acc : 0.67, test_acc : 0.60
K: 58, tr_acc : 0.66, test_acc : 0.62
K: 59, tr_acc : 0.67, test_acc : 0.62
K: 60, tr_acc : 0.66, test_acc : 0.62
K: 61, tr_acc : 0.67, test_acc : 0.60
K: 62, tr_acc : 0.66, test_acc : 0.61
K: 63, tr_acc : 0.66, test_acc : 0.60
K: 64, tr_acc : 0.65, test_acc : 0.60
K: 65, tr_acc : 0.66, test_acc : 0.61
K: 66, tr_acc : 0.66, test_acc : 0.61
K: 67, tr_acc : 0.66, test_acc : 0.60
K: 68, tr_acc : 0.65, test_acc : 0.60
K: 69, tr_acc : 0.66, test_acc : 0.61
K: 70, tr_acc : 0.66, test_acc : 0.59
K: 71, tr_acc : 0.65, test_acc : 0.60
K: 72, tr_acc : 0.65, test_acc : 0.59
K: 73, tr_acc : 0.65, test_acc : 0.60
K: 74, tr_acc : 0.65, test_acc : 0.59
K: 75, tr_acc : 0.65, test_acc : 0.59
K: 76, tr_acc : 0.65, test_acc : 0.59
K: 77, tr_acc : 0.66, test_acc : 0.59
K: 78, tr_acc : 0.65, test_acc : 0.59
K: 79, tr_acc : 0.66, test_acc : 0.61
K: 80, tr_acc : 0.66, test_acc : 0.61
K: 81, tr_acc : 0.67, test_acc : 0.61
K: 82, tr_acc : 0.67, test_acc : 0.61
K: 83, tr_acc : 0.67, test_acc : 0.61
K: 84, tr_acc : 0.67, test_acc : 0.60
K: 85, tr_acc : 0.66, test_acc : 0.61
K: 86, tr_acc : 0.67, test_acc : 0.62
K: 87, tr_acc : 0.66, test_acc : 0.61
K: 88, tr_acc : 0.66, test_acc : 0.62
K: 89, tr_acc : 0.66, test_acc : 0.62
K: 90, tr_acc : 0.66, test_acc : 0.62
K: 91, tr_acc : 0.66, test_acc : 0.61
K: 92, tr_acc : 0.66, test_acc : 0.62
K: 93, tr_acc : 0.66, test_acc : 0.62
K: 94, tr_acc : 0.66, test_acc : 0.62
K: 95, tr_acc : 0.66, test_acc : 0.62
K: 96, tr_acc : 0.66, test_acc : 0.62
K: 97, tr_acc : 0.66, test_acc : 0.62
K: 98, tr_acc : 0.66, test_acc : 0.62
K: 99, tr_acc : 0.66, test_acc : 0.62
K: 100, tr_acc : 0.66, test_acc : 0.62